/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShellCompromissoRouteImport } from './routes/_shell/compromisso'
import { Route as ShellCycleTimeRouteImport } from './routes/_shell/cycle-time'
import { Route as ShellRetrospectivasRouteImport } from './routes/_shell/retrospectivas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCompromissoRoute = ShellCompromissoRouteImport.update({
  id: '/compromisso',
  path: '/compromisso',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCycleTimeRoute = ShellCycleTimeRouteImport.update({
  id: '/cycle-time',
  path: '/cycle-time',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRetrospectivasRoute = ShellRetrospectivasRouteImport.update({
  id: '/retrospectivas',
  path: '/retrospectivas',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/compromisso': typeof ShellCompromissoRoute
  '/cycle-time': typeof ShellCycleTimeRoute
  '/retrospectivas': typeof ShellRetrospectivasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/compromisso': typeof ShellCompromissoRoute
  '/cycle-time': typeof ShellCycleTimeRoute
  '/retrospectivas': typeof ShellRetrospectivasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/_shell/compromisso': typeof ShellCompromissoRoute
  '/_shell/cycle-time': typeof ShellCycleTimeRoute
  '/_shell/retrospectivas': typeof ShellRetrospectivasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/compromisso'
    | '/cycle-time'
    | '/retrospectivas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/compromisso'
    | '/cycle-time'
    | '/retrospectivas'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/aceitar-convite'
    | '/admin'
    | '/_shell/compromisso'
    | '/_shell/cycle-time'
    | '/_shell/retrospectivas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AdminRoute: typeof AdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/compromisso': {
      id: '/_shell/compromisso'
      path: '/compromisso'
      fullPath: '/compromisso'
      preLoaderRoute: typeof ShellCompromissoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cycle-time': {
      id: '/_shell/cycle-time'
      path: '/cycle-time'
      fullPath: '/cycle-time'
      preLoaderRoute: typeof ShellCycleTimeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/retrospectivas': {
      id: '/_shell/retrospectivas'
      path: '/retrospectivas'
      fullPath: '/retrospectivas'
      preLoaderRoute: typeof ShellRetrospectivasRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCompromissoRoute: typeof ShellCompromissoRoute
  ShellCycleTimeRoute: typeof ShellCycleTimeRoute
  ShellRetrospectivasRoute: typeof ShellRetrospectivasRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCompromissoRoute: ShellCompromissoRoute,
  ShellCycleTimeRoute: ShellCycleTimeRoute,
  ShellRetrospectivasRoute: ShellRetrospectivasRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AdminRoute: AdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
